name: mi_card_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          weight: 400
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 400
#        - asset: fonts/SourceSansPro-Bold.ttf
#          weight: 700
#        - asset: fonts/SourceSansPro-BoldItalic.ttf
#          weight: 700
#          style: italic
#        - asset: fonts/SourceSansPro-Black.ttf
#          weight: 900
#        - asset: fonts/SourceSansPro-BlackItalic.ttf
#          weight: 900
#          style: italic
#        - asset: fonts/SourceSansPro-ExtraLight.ttf
#          weight: 400
#        - asset: fonts/SourceSansPro-ExtraLightItalic.ttf
#          weight: 200
#          style: italic
#        - asset: fonts/SourceSansPro-Italic.ttf
#          weight: 400
#          style: italic
#        - asset: fonts/SourceSansPro-Light.ttf
#          weight: 300
#        - asset: fonts/SourceSansPro-LightItalic.ttf
#          weight: 300
#          style: italic
#        - asset: fonts/SourceSansPro-SemiBold.ttf
#          weight: 600
#        - asset: fonts/SourceSansPro-SemiBoldItalic.ttf
#          weight: 600
#          style: italic